# Subreddit blacklist. use lowercase.
subreddits = [
    'diplomacy',
    'jerktalkdiamond',
    'earthporn',
    'wallpapers',
    'circlejerk',
    'deepdreampics', 
    'wallpaper',
    'removalbot',
    'transpassing', 
    'kerbalspaceprogram',
    'realsolarsystem',  
    'shittyadviceanimals',
    'imaginarymaps',
    'instahotties2',
    'eternityclub',
    'knowledgebombshell',
    'politicsmod',
    'gadgetsmod',
    'modtalk',
    'defaultmods',
    'gtavcustoms',
    '1911',
    'bottomlulz',
    'emobatman',
    'guns',
    'wsgy']
