# users blacklist. use lowercase.
users = [
    'amici_ursi',
    'captainnoboat',
    'corren_64',
    'crunchynutty',
    'dank_skeletons',
    'doesnthatefatties',
    'evosexybeast',
    'iamseiko',
    'ikibu',
    'justblue',
    'knowledgebombshell',
    'kritiosman',
    'kryso',
    'letthereber0ck',
    'plainchant',
    'puripurihakase',
    'removalbot',
    'removalbot_poster',
    'rpbot',
    'slanderousu',
    'thesemisoberone',
    'xfile345'
    ]
